dbtversion: 1.1.1

jobs:
 - name: daily
   schedule: 0 12 * * * # This example will run every day at 12:00pm
   targetName: dev
   timeout: 2h30m
   steps:
      - name: run models
        command: dbt run 
      - name: test models
        command: dbt test
